// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10loXVfASSuNq-_a0vOtPBaPWbWRI--Y',
    appId: '1:39206056356:web:08ed199ab14c095b02d131',
    messagingSenderId: '39206056356',
    projectId: 'seedemo-4ac2f',
    authDomain: 'seedemo-4ac2f.firebaseapp.com',
    storageBucket: 'seedemo-4ac2f.firebasestorage.app',
    measurementId: 'G-HKV7JFGFY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgYU6_SzNFFsn0ItlUwlKC_P4FQ_mOhQ',
    appId: '1:39206056356:android:07d2bae6a054004802d131',
    messagingSenderId: '39206056356',
    projectId: 'seedemo-4ac2f',
    storageBucket: 'seedemo-4ac2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi4XFvgHQOxkcr75j1T1vR8EdRxoe69r4',
    appId: '1:39206056356:ios:fefbd13191cbcddc02d131',
    messagingSenderId: '39206056356',
    projectId: 'seedemo-4ac2f',
    storageBucket: 'seedemo-4ac2f.firebasestorage.app',
    iosClientId: '39206056356-ovuh6karar3j53qt7f52bq2238f71b31.apps.googleusercontent.com',
    iosBundleId: 'com.example.forseeWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi4XFvgHQOxkcr75j1T1vR8EdRxoe69r4',
    appId: '1:39206056356:ios:fefbd13191cbcddc02d131',
    messagingSenderId: '39206056356',
    projectId: 'seedemo-4ac2f',
    storageBucket: 'seedemo-4ac2f.firebasestorage.app',
    iosClientId: '39206056356-ovuh6karar3j53qt7f52bq2238f71b31.apps.googleusercontent.com',
    iosBundleId: 'com.example.forseeWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBJVSN9B_GjMygYtAc-QGBLg2m_9pOuVA',
    appId: '1:39206056356:web:5f3fccbe1b1e9e7402d131',
    messagingSenderId: '39206056356',
    projectId: 'seedemo-4ac2f',
    authDomain: 'seedemo-4ac2f.firebaseapp.com',
    storageBucket: 'seedemo-4ac2f.firebasestorage.app',
    measurementId: 'G-TX21SPXZKM',
  );
}
